'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace WebService_Timbres
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimbresSoap", [Namespace]:="http://localhost/")>  _
    Partial Public Class Timbres
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private ConsultarTimbresOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GuardarTimbreOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FactuSax.My.MySettings.Default.FactuSax_WebService_Timbres_Timbres
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event ConsultarTimbresCompleted As ConsultarTimbresCompletedEventHandler
        
        '''<remarks/>
        Public Event GuardarTimbreCompleted As GuardarTimbreCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/ConsultarTimbres", RequestNamespace:="http://localhost/", ResponseNamespace:="http://localhost/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ConsultarTimbres(ByVal rfc As String) As Timbres1
            Dim results() As Object = Me.Invoke("ConsultarTimbres", New Object() {rfc})
            Return CType(results(0),Timbres1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub ConsultarTimbresAsync(ByVal rfc As String)
            Me.ConsultarTimbresAsync(rfc, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub ConsultarTimbresAsync(ByVal rfc As String, ByVal userState As Object)
            If (Me.ConsultarTimbresOperationCompleted Is Nothing) Then
                Me.ConsultarTimbresOperationCompleted = AddressOf Me.OnConsultarTimbresOperationCompleted
            End If
            Me.InvokeAsync("ConsultarTimbres", New Object() {rfc}, Me.ConsultarTimbresOperationCompleted, userState)
        End Sub
        
        Private Sub OnConsultarTimbresOperationCompleted(ByVal arg As Object)
            If (Not (Me.ConsultarTimbresCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent ConsultarTimbresCompleted(Me, New ConsultarTimbresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost/GuardarTimbre", RequestNamespace:="http://localhost/", ResponseNamespace:="http://localhost/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GuardarTimbre(ByVal rfc As String, ByVal movimiento As String, ByVal valor As Integer) As Timbres1
            Dim results() As Object = Me.Invoke("GuardarTimbre", New Object() {rfc, movimiento, valor})
            Return CType(results(0),Timbres1)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GuardarTimbreAsync(ByVal rfc As String, ByVal movimiento As String, ByVal valor As Integer)
            Me.GuardarTimbreAsync(rfc, movimiento, valor, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GuardarTimbreAsync(ByVal rfc As String, ByVal movimiento As String, ByVal valor As Integer, ByVal userState As Object)
            If (Me.GuardarTimbreOperationCompleted Is Nothing) Then
                Me.GuardarTimbreOperationCompleted = AddressOf Me.OnGuardarTimbreOperationCompleted
            End If
            Me.InvokeAsync("GuardarTimbre", New Object() {rfc, movimiento, valor}, Me.GuardarTimbreOperationCompleted, userState)
        End Sub
        
        Private Sub OnGuardarTimbreOperationCompleted(ByVal arg As Object)
            If (Not (Me.GuardarTimbreCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GuardarTimbreCompleted(Me, New GuardarTimbreCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Timbres", [Namespace]:="http://localhost/")>  _
    Partial Public Class Timbres1
        
        Private rFCField As String
        
        Private contratadasField As Long
        
        Private emisionesField As Long
        
        Private canceladasField As Long
        
        Private totalConsumidasField As Long
        
        Private disponiblesField As Long
        
        '''<remarks/>
        Public Property RFC() As String
            Get
                Return Me.rFCField
            End Get
            Set
                Me.rFCField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Contratadas() As Long
            Get
                Return Me.contratadasField
            End Get
            Set
                Me.contratadasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Emisiones() As Long
            Get
                Return Me.emisionesField
            End Get
            Set
                Me.emisionesField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Canceladas() As Long
            Get
                Return Me.canceladasField
            End Get
            Set
                Me.canceladasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property TotalConsumidas() As Long
            Get
                Return Me.totalConsumidasField
            End Get
            Set
                Me.totalConsumidasField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Disponibles() As Long
            Get
                Return Me.disponiblesField
            End Get
            Set
                Me.disponiblesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub ConsultarTimbresCompletedEventHandler(ByVal sender As Object, ByVal e As ConsultarTimbresCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class ConsultarTimbresCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timbres1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timbres1)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub GuardarTimbreCompletedEventHandler(ByVal sender As Object, ByVal e As GuardarTimbreCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GuardarTimbreCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Timbres1
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Timbres1)
            End Get
        End Property
    End Class
End Namespace
