'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos"),  _
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/Pagos", IsNullable:=false)>  _
Partial Public Class Pagos
    
    Private pagoField() As PagosPago
    
    Private versionField As String
    
    Public Sub New()
        MyBase.New
        Me.versionField = "1.0"
    End Sub
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Pago")>  _
    Public Property Pago() As PagosPago()
        Get
            Return Me.pagoField
        End Get
        Set
            Me.pagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos")>  _
Partial Public Class PagosPago
    
    Private doctoRelacionadoField() As PagosPagoDoctoRelacionado
    
    Private impuestosField() As PagosPagoImpuestos

    Private fechaPagoField As String

    Private formaDePagoPField As String

    Private monedaPField As String

    Private tipoCambioPField As Decimal
    
    Private tipoCambioPFieldSpecified As Boolean
    
    Private montoField As Decimal
    
    Private numOperacionField As String
    
    Private rfcEmisorCtaOrdField As String
    
    Private nomBancoOrdExtField As String
    
    Private ctaOrdenanteField As String
    
    Private rfcEmisorCtaBenField As String
    
    Private ctaBeneficiarioField As String
    
    Private tipoCadPagoField As c_TipoCadenaPago
    
    Private tipoCadPagoFieldSpecified As Boolean
    
    Private certPagoField() As Byte
    
    Private cadPagoField As String
    
    Private selloPagoField() As Byte
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("DoctoRelacionado")>  _
    Public Property DoctoRelacionado() As PagosPagoDoctoRelacionado()
        Get
            Return Me.doctoRelacionadoField
        End Get
        Set
            Me.doctoRelacionadoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Impuestos")>  _
    Public Property Impuestos() As PagosPagoImpuestos()
        Get
            Return Me.impuestosField
        End Get
        Set
            Me.impuestosField = value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property FechaPago() As String
        Get
            Return Me.fechaPagoField
        End Get
        Set
            Me.fechaPagoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property FormaDePagoP() As String
        Get
            Return Me.formaDePagoPField
        End Get
        Set
            Me.formaDePagoPField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property MonedaP() As String
        Get
            Return Me.monedaPField
        End Get
        Set
            Me.monedaPField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoCambioP() As Decimal
        Get
            Return Me.tipoCambioPField
        End Get
        Set
            Me.tipoCambioPField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipoCambioPSpecified() As Boolean
        Get
            Return Me.tipoCambioPFieldSpecified
        End Get
        Set
            Me.tipoCambioPFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Monto() As Decimal
        Get
            Return Me.montoField
        End Get
        Set
            Me.montoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NumOperacion() As String
        Get
            Return Me.numOperacionField
        End Get
        Set
            Me.numOperacionField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RfcEmisorCtaOrd() As String
        Get
            Return Me.rfcEmisorCtaOrdField
        End Get
        Set
            Me.rfcEmisorCtaOrdField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property NomBancoOrdExt() As String
        Get
            Return Me.nomBancoOrdExtField
        End Get
        Set
            Me.nomBancoOrdExtField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaOrdenante() As String
        Get
            Return Me.ctaOrdenanteField
        End Get
        Set
            Me.ctaOrdenanteField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property RfcEmisorCtaBen() As String
        Get
            Return Me.rfcEmisorCtaBenField
        End Get
        Set
            Me.rfcEmisorCtaBenField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CtaBeneficiario() As String
        Get
            Return Me.ctaBeneficiarioField
        End Get
        Set
            Me.ctaBeneficiarioField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoCadPago() As c_TipoCadenaPago
        Get
            Return Me.tipoCadPagoField
        End Get
        Set
            Me.tipoCadPagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipoCadPagoSpecified() As Boolean
        Get
            Return Me.tipoCadPagoFieldSpecified
        End Get
        Set
            Me.tipoCadPagoFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="base64Binary")>  _
    Public Property CertPago() As Byte()
        Get
            Return Me.certPagoField
        End Get
        Set
            Me.certPagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property CadPago() As String
        Get
            Return Me.cadPagoField
        End Get
        Set
            Me.cadPagoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="base64Binary")>  _
    Public Property SelloPago() As Byte()
        Get
            Return Me.selloPagoField
        End Get
        Set
            Me.selloPagoField = value
        End Set
    End Property
End Class

'''<comentarios/>
'''


<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos")>  _
Partial Public Class PagosPagoDoctoRelacionado
    
    Private idDocumentoField As String
    
    Private serieField As String
    
    Private folioField As String

    Private monedaDRField As String

    Private tipoCambioDRField As Decimal
    
    Private tipoCambioDRFieldSpecified As Boolean

    Private metodoDePagoDRField As String

    Private numParcialidadField As String
    
    Private impSaldoAntField As Decimal
    
    Private impSaldoAntFieldSpecified As Boolean
    
    Private impPagadoField As Decimal
    
    Private impPagadoFieldSpecified As Boolean
    
    Private impSaldoInsolutoField As Decimal
    
    Private impSaldoInsolutoFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property IdDocumento() As String
        Get
            Return Me.idDocumentoField
        End Get
        Set
            Me.idDocumentoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Serie() As String
        Get
            Return Me.serieField
        End Get
        Set
            Me.serieField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Folio() As String
        Get
            Return Me.folioField
        End Get
        Set
            Me.folioField = value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property MonedaDR() As String
        Get
            Return Me.monedaDRField
        End Get
        Set
            Me.monedaDRField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoCambioDR() As Decimal
        Get
            Return Me.tipoCambioDRField
        End Get
        Set
            Me.tipoCambioDRField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TipoCambioDRSpecified() As Boolean
        Get
            Return Me.tipoCambioDRFieldSpecified
        End Get
        Set
            Me.tipoCambioDRFieldSpecified = value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property MetodoDePagoDR() As String
        Get
            Return Me.metodoDePagoDRField
        End Get
        Set
            Me.metodoDePagoDRField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute(DataType:="integer")>  _
    Public Property NumParcialidad() As String
        Get
            Return Me.numParcialidadField
        End Get
        Set
            Me.numParcialidadField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ImpSaldoAnt() As Decimal
        Get
            Return Me.impSaldoAntField
        End Get
        Set
            Me.impSaldoAntField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ImpSaldoAntSpecified() As Boolean
        Get
            Return Me.impSaldoAntFieldSpecified
        End Get
        Set
            Me.impSaldoAntFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ImpPagado() As Decimal
        Get
            Return Me.impPagadoField
        End Get
        Set
            Me.impPagadoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ImpPagadoSpecified() As Boolean
        Get
            Return Me.impPagadoFieldSpecified
        End Get
        Set
            Me.impPagadoFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property ImpSaldoInsoluto() As Decimal
        Get
            Return Me.impSaldoInsolutoField
        End Get
        Set
            Me.impSaldoInsolutoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property ImpSaldoInsolutoSpecified() As Boolean
        Get
            Return Me.impSaldoInsolutoFieldSpecified
        End Get
        Set
            Me.impSaldoInsolutoFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos")>  _
Partial Public Class PagosPagoImpuestos
    
    Private retencionesField() As PagosPagoImpuestosRetencion
    
    Private trasladosField() As PagosPagoImpuestosTraslado
    
    Private totalImpuestosRetenidosField As Decimal
    
    Private totalImpuestosRetenidosFieldSpecified As Boolean
    
    Private totalImpuestosTrasladadosField As Decimal
    
    Private totalImpuestosTrasladadosFieldSpecified As Boolean
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=false)>  _
    Public Property Retenciones() As PagosPagoImpuestosRetencion()
        Get
            Return Me.retencionesField
        End Get
        Set
            Me.retencionesField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=false)>  _
    Public Property Traslados() As PagosPagoImpuestosTraslado()
        Get
            Return Me.trasladosField
        End Get
        Set
            Me.trasladosField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TotalImpuestosRetenidos() As Decimal
        Get
            Return Me.totalImpuestosRetenidosField
        End Get
        Set
            Me.totalImpuestosRetenidosField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TotalImpuestosRetenidosSpecified() As Boolean
        Get
            Return Me.totalImpuestosRetenidosFieldSpecified
        End Get
        Set
            Me.totalImpuestosRetenidosFieldSpecified = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TotalImpuestosTrasladados() As Decimal
        Get
            Return Me.totalImpuestosTrasladadosField
        End Get
        Set
            Me.totalImpuestosTrasladadosField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>  _
    Public Property TotalImpuestosTrasladadosSpecified() As Boolean
        Get
            Return Me.totalImpuestosTrasladadosFieldSpecified
        End Get
        Set
            Me.totalImpuestosTrasladadosFieldSpecified = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos")>  _
Partial Public Class PagosPagoImpuestosRetencion
    
    Private impuestoField As c_Impuesto
    
    Private importeField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Impuesto() As c_Impuesto
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/sitio_internet/cfd/catalogos")>  _
Public Enum c_Impuesto
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("001")>  _
    Item001
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("002")>  _
    Item002
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("003")>  _
    Item003
End Enum

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://www.sat.gob.mx/Pagos")>  _
Partial Public Class PagosPagoImpuestosTraslado
    
    Private impuestoField As c_Impuesto
    
    Private tipoFactorField As c_TipoFactor
    
    Private tasaOCuotaField As Decimal
    
    Private importeField As Decimal
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Impuesto() As c_Impuesto
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TipoFactor() As c_TipoFactor
        Get
            Return Me.tipoFactorField
        End Get
        Set
            Me.tipoFactorField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property TasaOCuota() As Decimal
        Get
            Return Me.tasaOCuotaField
        End Get
        Set
            Me.tasaOCuotaField = value
        End Set
    End Property
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>  _
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/sitio_internet/cfd/catalogos")>  _
Public Enum c_TipoFactor
    
    '''<comentarios/>
    Tasa
    
    '''<comentarios/>
    Cuota
    
    '''<comentarios/>
    Exento
End Enum

'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),  _
 System.SerializableAttribute(),  _
 System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/sitio_internet/cfd/catalogos/Pagos")>  _
Public Enum c_TipoCadenaPago
    
    '''<comentarios/>
    <System.Xml.Serialization.XmlEnumAttribute("01")>  _
    Item01
End Enum
