Option Strict Off
Option Explicit On
'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System.Xml.Schema
Imports System.Xml.Serialization

'
'Este código fuente fue generado automáticamente por xsd, Versión=4.6.1055.0.
'

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3"),
 System.Xml.Serialization.XmlRootAttribute([Namespace]:="http://www.sat.gob.mx/cfd/3", IsNullable:=False)>
Partial Public Class Comprobante

    Private cfdiRelacionadosField As ComprobanteCfdiRelacionados

    Private emisorField As ComprobanteEmisor

    Private receptorField As ComprobanteReceptor

    Private conceptosField() As ComprobanteConcepto

    Private impuestosField As ComprobanteImpuestos

    Private complementoField() As ComprobanteComplemento

    Private addendaField As ComprobanteAddenda

    Private versionField As String

    Private serieField As String

    Private folioField As String

    Private fechaField As Date

    Private selloField As String

    Private formaPagoField As String

    Private formaPagoFieldSpecified As Boolean

    Private noCertificadoField As String

    Private certificadoField As String

    Private condicionesDePagoField As String

    Private subTotalField As Decimal

    Private descuentoField As Decimal

    Private descuentoFieldSpecified As Boolean

    Private monedaField As String

    Private tipoCambioField As Decimal

    Private tipoCambioFieldSpecified As Boolean

    Private totalField As Decimal

    Private tipoDeComprobanteField As String

    Private metodoPagoField As String

    Private metodoPagoFieldSpecified As Boolean

    Private lugarExpedicionField As String

    Private confirmacionField As String

    <XmlAttribute("schemaLocation", Namespace:=XmlSchema.InstanceNamespace)>
    Public xsiSchemaLocation As String = "http://www.sat.gob.mx/sitio_internet/cfd/3/cfdv33.xsd"
    Public timbrefiscaldigital As TimbreFiscalDigital

    Public Sub New()
        MyBase.New
        Me.versionField = "3.3"
    End Sub

    '''<comentarios/>
    Public Property CfdiRelacionados() As ComprobanteCfdiRelacionados
        Get
            Return Me.cfdiRelacionadosField
        End Get
        Set
            Me.cfdiRelacionadosField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property Emisor() As ComprobanteEmisor
        Get
            Return Me.emisorField
        End Get
        Set
            Me.emisorField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property Receptor() As ComprobanteReceptor
        Get
            Return Me.receptorField
        End Get
        Set
            Me.receptorField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=False)>
    Public Property Conceptos() As ComprobanteConcepto()
        Get
            Return Me.conceptosField
        End Get
        Set
            Me.conceptosField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property Impuestos() As ComprobanteImpuestos
        Get
            Return Me.impuestosField
        End Get
        Set
            Me.impuestosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Complemento")>
    Public Property Complemento() As ComprobanteComplemento()
        Get
            Return Me.complementoField
        End Get
        Set
            Me.complementoField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property Addenda() As ComprobanteAddenda
        Get
            Return Me.addendaField
        End Get
        Set
            Me.addendaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Version() As String
        Get
            Return Me.versionField
        End Get
        Set
            Me.versionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Serie() As String
        Get
            Return Me.serieField
        End Get
        Set
            Me.serieField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Folio() As String
        Get
            Return Me.folioField
        End Get
        Set
            Me.folioField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Fecha() As Date
        Get
            Return Me.fechaField
        End Get
        Set
            Me.fechaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Sello() As String
        Get
            Return Me.selloField
        End Get
        Set
            Me.selloField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property FormaPago() As String
        Get
            Return Me.formaPagoField
        End Get
        Set
            Me.formaPagoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property FormaPagoSpecified() As Boolean
        Get
            Return Me.formaPagoFieldSpecified
        End Get
        Set
            Me.formaPagoFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NoCertificado() As String
        Get
            Return Me.noCertificadoField
        End Get
        Set
            Me.noCertificadoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Certificado() As String
        Get
            Return Me.certificadoField
        End Get
        Set
            Me.certificadoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property CondicionesDePago() As String
        Get
            Return Me.condicionesDePagoField
        End Get
        Set
            Me.condicionesDePagoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property SubTotal() As Decimal
        Get
            Return Me.subTotalField
        End Get
        Set
            Me.subTotalField = Value
        End Set
    End Property

    ''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Descuento() As Decimal
        Get
            Return Me.descuentoField
        End Get
        Set
            Me.descuentoField = Value
        End Set
    End Property

    ''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property DescuentoSpecified() As Boolean
        Get
            Return Me.descuentoFieldSpecified
        End Get
        Set
            Me.descuentoFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Moneda() As String
        Get
            Return Me.monedaField
        End Get
        Set
            Me.monedaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoCambio() As Decimal
        Get
            Return Me.tipoCambioField
        End Get
        Set
            Me.tipoCambioField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TipoCambioSpecified() As Boolean
        Get
            Return Me.tipoCambioFieldSpecified
        End Get
        Set
            Me.tipoCambioFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Total() As Decimal
        Get
            Return Me.totalField
        End Get
        Set
            Me.totalField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoDeComprobante() As String
        Get
            Return Me.tipoDeComprobanteField
        End Get
        Set
            Me.tipoDeComprobanteField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property MetodoPago() As String
        Get
            Return Me.metodoPagoField
        End Get
        Set
            Me.metodoPagoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property MetodoPagoSpecified() As Boolean
        Get
            Return Me.metodoPagoFieldSpecified
        End Get
        Set
            Me.metodoPagoFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property LugarExpedicion() As String
        Get
            Return Me.lugarExpedicionField
        End Get
        Set
            Me.lugarExpedicionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Confirmacion() As String
        Get
            Return Me.confirmacionField
        End Get
        Set
            Me.confirmacionField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteCfdiRelacionados

    Private cfdiRelacionadoField() As ComprobanteCfdiRelacionadosCfdiRelacionado

    Private tipoRelacionField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("CfdiRelacionado")>
    Public Property CfdiRelacionado() As ComprobanteCfdiRelacionadosCfdiRelacionado()
        Get
            Return Me.cfdiRelacionadoField
        End Get
        Set
            Me.cfdiRelacionadoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoRelacion() As String
        Get
            Return Me.tipoRelacionField
        End Get
        Set
            Me.tipoRelacionField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteCfdiRelacionadosCfdiRelacionado

    Private uUIDField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property UUID() As String
        Get
            Return Me.uUIDField
        End Get
        Set
            Me.uUIDField = Value
        End Set
    End Property
End Class

'''<comentarios/>

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteEmisor

    Private rfcField As String

    Private nombreField As String

    Private regimenFiscalField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Rfc() As String
        Get
            Return Me.rfcField
        End Get
        Set
            Me.rfcField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Nombre() As String
        Get
            Return Me.nombreField
        End Get
        Set
            Me.nombreField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property RegimenFiscal() As String
        Get
            Return Me.regimenFiscalField
        End Get
        Set
            Me.regimenFiscalField = Value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteReceptor

    Private rfcField As String

    Private nombreField As String

    Private residenciaFiscalField As String

    Private residenciaFiscalFieldSpecified As Boolean

    Private numRegIdTribField As String

    Private usoCFDIField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Rfc() As String
        Get
            Return Me.rfcField
        End Get
        Set
            Me.rfcField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Nombre() As String
        Get
            Return Me.nombreField
        End Get
        Set
            Me.nombreField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ResidenciaFiscal() As String
        Get
            Return Me.residenciaFiscalField
        End Get
        Set
            Me.residenciaFiscalField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ResidenciaFiscalSpecified() As Boolean
        Get
            Return Me.residenciaFiscalFieldSpecified
        End Get
        Set
            Me.residenciaFiscalFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NumRegIdTrib() As String
        Get
            Return Me.numRegIdTribField
        End Get
        Set
            Me.numRegIdTribField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property UsoCFDI() As String
        Get
            Return Me.usoCFDIField
        End Get
        Set
            Me.usoCFDIField = Value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConcepto

    Private impuestosField As ComprobanteConceptoImpuestos

    Private informacionAduaneraField() As ComprobanteConceptoInformacionAduanera

    Private cuentaPredialField As ComprobanteConceptoCuentaPredial

    Private complementoConceptoField As ComprobanteConceptoComplementoConcepto

    Private parteField() As ComprobanteConceptoParte

    Private claveProdServField As String

    Private noIdentificacionField As String

    Private cantidadField As Decimal

    Private claveUnidadField As String

    Private unidadField As String

    Private descripcionField As String

    Private valorUnitarioField As Decimal

    Private importeField As Decimal

    Private descuentoField As Decimal

    Private descuentoFieldSpecified As Boolean

    '''<comentarios/>
    Public Property Impuestos() As ComprobanteConceptoImpuestos
        Get
            Return Me.impuestosField
        End Get
        Set
            Me.impuestosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>
    Public Property InformacionAduanera() As ComprobanteConceptoInformacionAduanera()
        Get
            Return Me.informacionAduaneraField
        End Get
        Set
            Me.informacionAduaneraField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property CuentaPredial() As ComprobanteConceptoCuentaPredial
        Get
            Return Me.cuentaPredialField
        End Get
        Set
            Me.cuentaPredialField = Value
        End Set
    End Property

    '''<comentarios/>
    Public Property ComplementoConcepto() As ComprobanteConceptoComplementoConcepto
        Get
            Return Me.complementoConceptoField
        End Get
        Set
            Me.complementoConceptoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("Parte")>
    Public Property Parte() As ComprobanteConceptoParte()
        Get
            Return Me.parteField
        End Get
        Set
            Me.parteField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ClaveProdServ() As String
        Get
            Return Me.claveProdServField
        End Get
        Set
            Me.claveProdServField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NoIdentificacion() As String
        Get
            Return Me.noIdentificacionField
        End Get
        Set
            Me.noIdentificacionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Cantidad() As Decimal
        Get
            Return Me.cantidadField
        End Get
        Set
            Me.cantidadField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ClaveUnidad() As String
        Get
            Return Me.claveUnidadField
        End Get
        Set
            Me.claveUnidadField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Unidad() As String
        Get
            Return Me.unidadField
        End Get
        Set
            Me.unidadField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set
            Me.descripcionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ValorUnitario() As Decimal
        Get
            Return Me.valorUnitarioField
        End Get
        Set
            Me.valorUnitarioField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Descuento() As Decimal
        Get
            Return Me.descuentoField
        End Get
        Set
            Me.descuentoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property DescuentoSpecified() As Boolean
        Get
            Return Me.descuentoFieldSpecified
        End Get
        Set
            Me.descuentoFieldSpecified = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoImpuestos

    Private trasladosField() As ComprobanteConceptoImpuestosTraslado

    Private retencionesField() As ComprobanteConceptoImpuestosRetencion

    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=False)>
    Public Property Traslados() As ComprobanteConceptoImpuestosTraslado()
        Get
            Return Me.trasladosField
        End Get
        Set
            Me.trasladosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=False)>
    Public Property Retenciones() As ComprobanteConceptoImpuestosRetencion()
        Get
            Return Me.retencionesField
        End Get
        Set
            Me.retencionesField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoImpuestosTraslado

    Private baseField As Decimal

    Private impuestoField As String

    Private tipoFactorField As String

    Private tasaOCuotaField As Decimal

    Private tasaOCuotaFieldSpecified As Boolean

    Private importeField As Decimal

    Private importeFieldSpecified As Boolean

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Base() As Decimal
        Get
            Return Me.baseField
        End Get
        Set
            Me.baseField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Impuesto() As String
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoFactor() As String
        Get
            Return Me.tipoFactorField
        End Get
        Set
            Me.tipoFactorField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TasaOCuota() As Decimal
        Get
            Return Me.tasaOCuotaField
        End Get
        Set
            Me.tasaOCuotaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TasaOCuotaSpecified() As Boolean
        Get
            Return Me.tasaOCuotaFieldSpecified
        End Get
        Set
            Me.tasaOCuotaFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ImporteSpecified() As Boolean
        Get
            Return Me.importeFieldSpecified
        End Get
        Set
            Me.importeFieldSpecified = Value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoImpuestosRetencion

    Private baseField As Decimal

    Private impuestoField As String

    Private tipoFactorField As String

    Private tasaOCuotaField As Decimal

    Private importeField As Decimal

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Base() As Decimal
        Get
            Return Me.baseField
        End Get
        Set
            Me.baseField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Impuesto() As String
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoFactor() As String
        Get
            Return Me.tipoFactorField
        End Get
        Set
            Me.tipoFactorField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TasaOCuota() As Decimal
        Get
            Return Me.tasaOCuotaField
        End Get
        Set
            Me.tasaOCuotaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoInformacionAduanera

    Private numeroPedimentoField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NumeroPedimento() As String
        Get
            Return Me.numeroPedimentoField
        End Get
        Set
            Me.numeroPedimentoField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoCuentaPredial

    Private numeroField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Numero() As String
        Get
            Return Me.numeroField
        End Get
        Set
            Me.numeroField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoComplementoConcepto

    Private anyField() As System.Xml.XmlElement

    '''<comentarios/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoParte

    Private informacionAduaneraField() As ComprobanteConceptoParteInformacionAduanera

    Private claveProdServField As String

    Private noIdentificacionField As String

    Private cantidadField As Decimal

    Private unidadField As String

    Private descripcionField As String

    Private valorUnitarioField As Decimal

    Private valorUnitarioFieldSpecified As Boolean

    Private importeField As Decimal

    Private importeFieldSpecified As Boolean

    '''<comentarios/>
    <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>
    Public Property InformacionAduanera() As ComprobanteConceptoParteInformacionAduanera()
        Get
            Return Me.informacionAduaneraField
        End Get
        Set
            Me.informacionAduaneraField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ClaveProdServ() As String
        Get
            Return Me.claveProdServField
        End Get
        Set
            Me.claveProdServField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NoIdentificacion() As String
        Get
            Return Me.noIdentificacionField
        End Get
        Set
            Me.noIdentificacionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Cantidad() As Decimal
        Get
            Return Me.cantidadField
        End Get
        Set
            Me.cantidadField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Unidad() As String
        Get
            Return Me.unidadField
        End Get
        Set
            Me.unidadField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Descripcion() As String
        Get
            Return Me.descripcionField
        End Get
        Set
            Me.descripcionField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property ValorUnitario() As Decimal
        Get
            Return Me.valorUnitarioField
        End Get
        Set
            Me.valorUnitarioField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ValorUnitarioSpecified() As Boolean
        Get
            Return Me.valorUnitarioFieldSpecified
        End Get
        Set
            Me.valorUnitarioFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property ImporteSpecified() As Boolean
        Get
            Return Me.importeFieldSpecified
        End Get
        Set
            Me.importeFieldSpecified = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteConceptoParteInformacionAduanera

    Private numeroPedimentoField As String

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property NumeroPedimento() As String
        Get
            Return Me.numeroPedimentoField
        End Get
        Set
            Me.numeroPedimentoField = Value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>


'''<comentarios/>


'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteImpuestosRetencion

    Private impuestoField As String

    Private importeField As Decimal

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Impuesto() As String
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteImpuestosTraslado

    Private impuestoField As String

    Private tipoFactorField As String

    Private tasaOCuotaField As Decimal

    Private importeField As Decimal

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Impuesto() As String
        Get
            Return Me.impuestoField
        End Get
        Set
            Me.impuestoField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TipoFactor() As String
        Get
            Return Me.tipoFactorField
        End Get
        Set
            Me.tipoFactorField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TasaOCuota() As Decimal
        Get
            Return Me.tasaOCuotaField
        End Get
        Set
            Me.tasaOCuotaField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property Importe() As Decimal
        Get
            Return Me.importeField
        End Get
        Set
            Me.importeField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteComplemento

    Private anyField() As System.Xml.XmlElement

    '''<comentarios/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = Value
        End Set
    End Property
End Class

'''<comentarios/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0"),
 System.SerializableAttribute(),
 System.Diagnostics.DebuggerStepThroughAttribute(),
 System.ComponentModel.DesignerCategoryAttribute("code"),
 System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=True, [Namespace]:="http://www.sat.gob.mx/cfd/3")>
Partial Public Class ComprobanteAddenda

    Private anyField() As System.Xml.XmlElement

    '''<comentarios/>
    <System.Xml.Serialization.XmlAnyElementAttribute()>
    Public Property Any() As System.Xml.XmlElement()
        Get
            Return Me.anyField
        End Get
        Set
            Me.anyField = Value
        End Set
    End Property
End Class
Partial Public Class ComprobanteImpuestos

    Private retencionesField() As ComprobanteImpuestosRetencion

    Private trasladosField() As ComprobanteImpuestosTraslado

    Private totalImpuestosRetenidosField As Decimal

    Private totalImpuestosRetenidosFieldSpecified As Boolean

    Private totalImpuestosTrasladadosField As Decimal

    Private totalImpuestosTrasladadosFieldSpecified As Boolean

    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=False)>
    Public Property Retenciones() As ComprobanteImpuestosRetencion()
        Get
            Return Me.retencionesField
        End Get
        Set
            Me.retencionesField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=False)>
    Public Property Traslados() As ComprobanteImpuestosTraslado()
        Get
            Return Me.trasladosField
        End Get
        Set
            Me.trasladosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TotalImpuestosRetenidos() As Decimal
        Get
            Return Me.totalImpuestosRetenidosField
        End Get
        Set
            Me.totalImpuestosRetenidosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TotalImpuestosRetenidosSpecified() As Boolean
        Get
            Return Me.totalImpuestosRetenidosFieldSpecified
        End Get
        Set
            Me.totalImpuestosRetenidosFieldSpecified = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlAttributeAttribute()>
    Public Property TotalImpuestosTrasladados() As Decimal
        Get
            Return Me.totalImpuestosTrasladadosField
        End Get
        Set
            Me.totalImpuestosTrasladadosField = Value
        End Set
    End Property

    '''<comentarios/>
    <System.Xml.Serialization.XmlIgnoreAttribute()>
    Public Property TotalImpuestosTrasladadosSpecified() As Boolean
        Get
            Return Me.totalImpuestosTrasladadosFieldSpecified
        End Get
        Set
            Me.totalImpuestosTrasladadosFieldSpecified = Value
        End Set
    End Property
End Class

'''<comentarios/>


'''<comentarios/>


'''<comentarios/>


'''<comentarios/>


'''<comentarios/>

