'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "Funcionalidad para autoguardar My.Settings"
#If _MYTYPE = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MYTYPE = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://74.208.239.165/WebService_Timbres/Timbres.asmx")>
        Public ReadOnly Property FactuSax_WebService_Timbres_Timbres() As String
            Get
                Return CType(Me("FactuSax_WebService_Timbres_Timbres"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://pruebastimbrado.expidetufactura.com.mx:8451/preproduccion/TimbradoWS")>
        Public ReadOnly Property FactuSax_ExpideTuFactura_TimbradoWSService() As String
            Get
                Return CType(Me("FactuSax_ExpideTuFactura_TimbradoWSService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://74.208.239.165/WebService_iSISLAB/Actualizar_Estatus.asmx")>
        Public ReadOnly Property FactuSax_WebService_InsercionSISLAB_Actualizar_Estatus() As String
            Get
                Return CType(Me("FactuSax_WebService_InsercionSISLAB_Actualizar_Estatus"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("http://localhost:13675/Actualizar_Estatus.asmx")>
        Public ReadOnly Property FactuSax_localhostSISLAB_Actualizar_Estatus() As String
            Get
                Return CType(Me("FactuSax_localhostSISLAB_Actualizar_Estatus"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://timbradodp.expidetufactura.com.mx:8453/timbrado/TimbradoWS")>
        Public ReadOnly Property FactuSax_XpdProduccion_TimbradoWSService() As String
            Get
                Return CType(Me("FactuSax_XpdProduccion_TimbradoWSService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://appliance-qa.expidetufactura.com.mx:8585/CoreTimbrado.test/TimbradoWSSoap" &
            "Single")>
        Public ReadOnly Property FactuSax_xpdPruebas4_0_TimbradoWSSoapSingle() As String
            Get
                Return CType(Me("FactuSax_xpdPruebas4_0_TimbradoWSSoapSingle"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap" &
            "ws")>
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd_Produccion_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd_Produccion_CancelacionPortService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap" &
            "ws")>
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd_produccion_v3_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd_produccion_v3_CancelacionPortServi" &
                    "ce"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap" &
            "ws")>
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd_CancelacionPortService"), String)
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(),
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap" &
            "ws")>
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd1_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd1_CancelacionPortService"), String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap"& _ 
            "ws")>  _
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd_CancelacionPortService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://cancelacionxpd.expidetufactura.com.mx:1443/coreCancelacionProduccion/soap"& _ 
            "ws")>  _
        Public ReadOnly Property FactuSax_mx_com_expidetufactura_cancelacionxpd1_CancelacionPortService() As String
            Get
                Return CType(Me("FactuSax_mx_com_expidetufactura_cancelacionxpd1_CancelacionPortService"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>
        Friend ReadOnly Property Settings() As Global.FactuSax.My.MySettings
            Get
                Return Global.FactuSax.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
