'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace xpdPruebas4_0
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="TimbradoWSSoapSingleSoapBinding", [Namespace]:="http://service.timbrado.xpd.mx/"),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(responseTimbrarSingle))>  _
    Partial Public Class TimbradoWSSoapSingle
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private validarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private timbrarOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FactuSax.My.MySettings.Default.FactuSax_xpdPruebas4_0_TimbradoWSSoapSingle
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event validarCompleted As validarCompletedEventHandler
        
        '''<remarks/>
        Public Event timbrarCompleted As timbrarCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.timbrado.xpd.mx/", ResponseNamespace:="http://service.timbrado.xpd.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function validar(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasena As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> ByVal cfdi() As Byte, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal isEstatusSat As Boolean) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseValidar
            Dim results() As Object = Me.Invoke("validar", New Object() {usuario, contrasena, cfdi, isEstatusSat})
            Return CType(results(0),responseValidar)
        End Function
        
        '''<remarks/>
        Public Overloads Sub validarAsync(ByVal usuario As String, ByVal contrasena As String, ByVal cfdi() As Byte, ByVal isEstatusSat As Boolean)
            Me.validarAsync(usuario, contrasena, cfdi, isEstatusSat, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub validarAsync(ByVal usuario As String, ByVal contrasena As String, ByVal cfdi() As Byte, ByVal isEstatusSat As Boolean, ByVal userState As Object)
            If (Me.validarOperationCompleted Is Nothing) Then
                Me.validarOperationCompleted = AddressOf Me.OnvalidarOperationCompleted
            End If
            Me.InvokeAsync("validar", New Object() {usuario, contrasena, cfdi, isEstatusSat}, Me.validarOperationCompleted, userState)
        End Sub
        
        Private Sub OnvalidarOperationCompleted(ByVal arg As Object)
            If (Not (Me.validarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent validarCompleted(Me, New validarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://service.timbrado.xpd.mx/", ResponseNamespace:="http://service.timbrado.xpd.mx/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function timbrar(<System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal usuario As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> ByVal contrasena As String, <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")> ByVal cfdi() As Byte) As <System.Xml.Serialization.XmlElementAttribute("return", Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)> responseTimbrar
            Dim results() As Object = Me.Invoke("timbrar", New Object() {usuario, contrasena, cfdi})
            Return CType(results(0),responseTimbrar)
        End Function
        
        '''<remarks/>
        Public Overloads Sub timbrarAsync(ByVal usuario As String, ByVal contrasena As String, ByVal cfdi() As Byte)
            Me.timbrarAsync(usuario, contrasena, cfdi, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub timbrarAsync(ByVal usuario As String, ByVal contrasena As String, ByVal cfdi() As Byte, ByVal userState As Object)
            If (Me.timbrarOperationCompleted Is Nothing) Then
                Me.timbrarOperationCompleted = AddressOf Me.OntimbrarOperationCompleted
            End If
            Me.InvokeAsync("timbrar", New Object() {usuario, contrasena, cfdi}, Me.timbrarOperationCompleted, userState)
        End Sub
        
        Private Sub OntimbrarOperationCompleted(ByVal arg As Object)
            If (Not (Me.timbrarCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent timbrarCompleted(Me, New timbrarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.timbrado.xpd.mx/")>  _
    Partial Public Class responseValidar
        
        Private transaccionField As String
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private hashField As String
        
        Private cadenaOriginalField As String
        
        Private uuidField As String
        
        Private provCertifField As String
        
        Private hashTfdField As String
        
        Private cadenaOriginalTfdField As String
        
        Private complementosField As String
        
        Private estructuraField As singleResponse
        
        Private selloCfdiField As singleResponse
        
        Private csdEmisorField As singleResponse
        
        Private validacionCfdiField As singleResponse
        
        Private validacionComplementosField As singleResponse
        
        Private validacionTimbreFiscalField As singleResponse
        
        Private validacionSatField As singleResponse
        
        Private acuseSatField As acuse
        
        Private comprobanteField As comprobante
        
        Private retencionesField As retenciones1
        
        Private notificacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transaccion() As String
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property hash() As String
            Get
                Return Me.hashField
            End Get
            Set
                Me.hashField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cadenaOriginal() As String
            Get
                Return Me.cadenaOriginalField
            End Get
            Set
                Me.cadenaOriginalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property provCertif() As String
            Get
                Return Me.provCertifField
            End Get
            Set
                Me.provCertifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property hashTfd() As String
            Get
                Return Me.hashTfdField
            End Get
            Set
                Me.hashTfdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property cadenaOriginalTfd() As String
            Get
                Return Me.cadenaOriginalTfdField
            End Get
            Set
                Me.cadenaOriginalTfdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property complementos() As String
            Get
                Return Me.complementosField
            End Get
            Set
                Me.complementosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estructura() As singleResponse
            Get
                Return Me.estructuraField
            End Get
            Set
                Me.estructuraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property selloCfdi() As singleResponse
            Get
                Return Me.selloCfdiField
            End Get
            Set
                Me.selloCfdiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property csdEmisor() As singleResponse
            Get
                Return Me.csdEmisorField
            End Get
            Set
                Me.csdEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validacionCfdi() As singleResponse
            Get
                Return Me.validacionCfdiField
            End Get
            Set
                Me.validacionCfdiField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validacionComplementos() As singleResponse
            Get
                Return Me.validacionComplementosField
            End Get
            Set
                Me.validacionComplementosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validacionTimbreFiscal() As singleResponse
            Get
                Return Me.validacionTimbreFiscalField
            End Get
            Set
                Me.validacionTimbreFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validacionSat() As singleResponse
            Get
                Return Me.validacionSatField
            End Get
            Set
                Me.validacionSatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property acuseSat() As acuse
            Get
                Return Me.acuseSatField
            End Get
            Set
                Me.acuseSatField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
        Public Property Comprobante() As comprobante
            Get
                Return Me.comprobanteField
            End Get
            Set
                Me.comprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
        Public Property Retenciones() As retenciones1
            Get
                Return Me.retencionesField
            End Get
            Set
                Me.retencionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property notificacion() As String
            Get
                Return Me.notificacionField
            End Get
            Set
                Me.notificacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.timbrado.xpd.mx/")>  _
    Partial Public Class singleResponse
        
        Private codigoField As String
        
        Private mensajeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(responseTimbrar)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.timbrado.xpd.mx/")>  _
    Partial Public Class responseTimbrarSingle
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private timbreField As String
        
        Private uuidField As String
        
        Private hashField As String
        
        Private transaccionField As String
        
        Private notificacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property timbre() As String
            Get
                Return Me.timbreField
            End Get
            Set
                Me.timbreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property hash() As String
            Get
                Return Me.hashField
            End Get
            Set
                Me.hashField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property transaccion() As String
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property notificacion() As String
            Get
                Return Me.notificacionField
            End Get
            Set
                Me.notificacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.timbrado.xpd.mx/")>  _
    Partial Public Class responseTimbrar
        Inherits responseTimbrarSingle
        
        Private codigoPdfField As String
        
        Private pdfField() As Byte
        
        Private codigoMailField As String
        
        Private codigoSmsField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoPdf() As String
            Get
                Return Me.codigoPdfField
            End Get
            Set
                Me.codigoPdfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType:="base64Binary")>  _
        Public Property pdf() As Byte()
            Get
                Return Me.pdfField
            End Get
            Set
                Me.pdfField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoMail() As String
            Get
                Return Me.codigoMailField
            End Get
            Set
                Me.codigoMailField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoSms() As String
            Get
                Return Me.codigoSmsField
            End Get
            Set
                Me.codigoSmsField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class impRetenidos
        
        Private baseRetField As String
        
        Private impuestoRetField As String
        
        Private montoRetField As String
        
        Private tipoPagoRetField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property BaseRet() As String
            Get
                Return Me.baseRetField
            End Get
            Set
                Me.baseRetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ImpuestoRet() As String
            Get
                Return Me.impuestoRetField
            End Get
            Set
                Me.impuestoRetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MontoRet() As String
            Get
                Return Me.montoRetField
            End Get
            Set
                Me.montoRetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoPagoRet() As String
            Get
                Return Me.tipoPagoRetField
            End Get
            Set
                Me.tipoPagoRetField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class totales
        
        Private impRetenidosField() As impRetenidos
        
        Private iSRCorrespondienteField As String
        
        Private montoTotExentField As String
        
        Private montoTotGravField As String
        
        Private montoTotOperacionField As String
        
        Private montoTotRetField As String
        
        Private utilidadBimestralField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ImpRetenidos")>  _
        Public Property ImpRetenidos() As impRetenidos()
            Get
                Return Me.impRetenidosField
            End Get
            Set
                Me.impRetenidosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ISRCorrespondiente() As String
            Get
                Return Me.iSRCorrespondienteField
            End Get
            Set
                Me.iSRCorrespondienteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MontoTotExent() As String
            Get
                Return Me.montoTotExentField
            End Get
            Set
                Me.montoTotExentField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MontoTotGrav() As String
            Get
                Return Me.montoTotGravField
            End Get
            Set
                Me.montoTotGravField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MontoTotOperacion() As String
            Get
                Return Me.montoTotOperacionField
            End Get
            Set
                Me.montoTotOperacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MontoTotRet() As String
            Get
                Return Me.montoTotRetField
            End Get
            Set
                Me.montoTotRetField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UtilidadBimestral() As String
            Get
                Return Me.utilidadBimestralField
            End Get
            Set
                Me.utilidadBimestralField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class periodo
        
        Private ejercicioField As String
        
        Private mesFinField As String
        
        Private mesIniField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Ejercicio() As String
            Get
                Return Me.ejercicioField
            End Get
            Set
                Me.ejercicioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MesFin() As String
            Get
                Return Me.mesFinField
            End Get
            Set
                Me.mesFinField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MesIni() As String
            Get
                Return Me.mesIniField
            End Get
            Set
                Me.mesIniField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class nacional
        
        Private curpRField As String
        
        Private domicilioFiscalRField As String
        
        Private nomDenRazSocRField As String
        
        Private rfcRField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CurpR() As String
            Get
                Return Me.curpRField
            End Get
            Set
                Me.curpRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DomicilioFiscalR() As String
            Get
                Return Me.domicilioFiscalRField
            End Get
            Set
                Me.domicilioFiscalRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NomDenRazSocR() As String
            Get
                Return Me.nomDenRazSocRField
            End Get
            Set
                Me.nomDenRazSocRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcR() As String
            Get
                Return Me.rfcRField
            End Get
            Set
                Me.rfcRField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class extranjero
        
        Private nomDenRazSocRField As String
        
        Private numRegIdTribRField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NomDenRazSocR() As String
            Get
                Return Me.nomDenRazSocRField
            End Get
            Set
                Me.nomDenRazSocRField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NumRegIdTribR() As String
            Get
                Return Me.numRegIdTribRField
            End Get
            Set
                Me.numRegIdTribRField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="receptor", [Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class receptor1
        
        Private extranjeroField As extranjero
        
        Private nacionalField As nacional
        
        Private nacionalidadRField As String
        
        '''<remarks/>
        Public Property Extranjero() As extranjero
            Get
                Return Me.extranjeroField
            End Get
            Set
                Me.extranjeroField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Nacional() As nacional
            Get
                Return Me.nacionalField
            End Get
            Set
                Me.nacionalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NacionalidadR() As String
            Get
                Return Me.nacionalidadRField
            End Get
            Set
                Me.nacionalidadRField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="emisor", [Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class emisor1
        
        Private nomDenRazSocEField As String
        
        Private regimenFiscalEField As String
        
        Private rfcEField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NomDenRazSocE() As String
            Get
                Return Me.nomDenRazSocEField
            End Get
            Set
                Me.nomDenRazSocEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RegimenFiscalE() As String
            Get
                Return Me.regimenFiscalEField
            End Get
            Set
                Me.regimenFiscalEField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcE() As String
            Get
                Return Me.rfcEField
            End Get
            Set
                Me.rfcEField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class cfdiRetenRelacionados
        
        Private tipoRelacionField As String
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoRelacion() As String
            Get
                Return Me.tipoRelacionField
            End Get
            Set
                Me.tipoRelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="retenciones", [Namespace]:="http://www.sat.gob.mx/esquemas/retencionpago/2")>  _
    Partial Public Class retenciones1
        
        Private cfdiRetenRelacionadosField As cfdiRetenRelacionados
        
        Private emisorField As emisor1
        
        Private receptorField As receptor1
        
        Private periodoField As periodo
        
        Private totalesField As totales
        
        Private complementoField() As timbreFiscalDigital
        
        Private certificadoField As String
        
        Private cveRetencField As String
        
        Private descRetencField As String
        
        Private fechaExpField As String
        
        Private folioIntField As String
        
        Private lugarExpRetencField As String
        
        Private noCertificadoField As String
        
        Private selloField As String
        
        Private versionField As String
        
        '''<remarks/>
        Public Property CfdiRetenRelacionados() As cfdiRetenRelacionados
            Get
                Return Me.cfdiRetenRelacionadosField
            End Get
            Set
                Me.cfdiRetenRelacionadosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Emisor() As emisor1
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receptor() As receptor1
            Get
                Return Me.receptorField
            End Get
            Set
                Me.receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Periodo() As periodo
            Get
                Return Me.periodoField
            End Get
            Set
                Me.periodoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Totales() As totales
            Get
                Return Me.totalesField
            End Get
            Set
                Me.totalesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("TimbreFiscalDigital", [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital", IsNullable:=false)>  _
        Public Property Complemento() As timbreFiscalDigital()
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Certificado() As String
            Get
                Return Me.certificadoField
            End Get
            Set
                Me.certificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CveRetenc() As String
            Get
                Return Me.cveRetencField
            End Get
            Set
                Me.cveRetencField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DescRetenc() As String
            Get
                Return Me.descRetencField
            End Get
            Set
                Me.descRetencField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FechaExp() As String
            Get
                Return Me.fechaExpField
            End Get
            Set
                Me.fechaExpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FolioInt() As String
            Get
                Return Me.folioIntField
            End Get
            Set
                Me.folioIntField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property LugarExpRetenc() As String
            Get
                Return Me.lugarExpRetencField
            End Get
            Set
                Me.lugarExpRetencField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NoCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Sello() As String
            Get
                Return Me.selloField
            End Get
            Set
                Me.selloField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital")>  _
    Partial Public Class timbreFiscalDigital
        
        Private versionField As String
        
        Private uUIDField As String
        
        Private fechaTimbradoField As String
        
        Private rfcProvCertifField As String
        
        Private leyendaField As String
        
        Private selloCFDField As String
        
        Private noCertificadoSATField As String
        
        Private selloSATField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FechaTimbrado() As String
            Get
                Return Me.fechaTimbradoField
            End Get
            Set
                Me.fechaTimbradoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcProvCertif() As String
            Get
                Return Me.rfcProvCertifField
            End Get
            Set
                Me.rfcProvCertifField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Leyenda() As String
            Get
                Return Me.leyendaField
            End Get
            Set
                Me.leyendaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property SelloCFD() As String
            Get
                Return Me.selloCFDField
            End Get
            Set
                Me.selloCFDField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NoCertificadoSAT() As String
            Get
                Return Me.noCertificadoSATField
            End Get
            Set
                Me.noCertificadoSATField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property SelloSAT() As String
            Get
                Return Me.selloSATField
            End Get
            Set
                Me.selloSATField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class impuestos
        
        Private retencionesField() As retencion
        
        Private trasladosField() As traslado
        
        Private totalImpuestosRetenidosField As String
        
        Private totalImpuestosTrasladadosField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=false)>  _
        Public Property Retenciones() As retencion()
            Get
                Return Me.retencionesField
            End Get
            Set
                Me.retencionesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=false)>  _
        Public Property Traslados() As traslado()
            Get
                Return Me.trasladosField
            End Get
            Set
                Me.trasladosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TotalImpuestosRetenidos() As String
            Get
                Return Me.totalImpuestosRetenidosField
            End Get
            Set
                Me.totalImpuestosRetenidosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TotalImpuestosTrasladados() As String
            Get
                Return Me.totalImpuestosTrasladadosField
            End Get
            Set
                Me.totalImpuestosTrasladadosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class retencion
        
        Private baseField As String
        
        Private importeField As String
        
        Private impuestoField As String
        
        Private tasaOCuotaField As String
        
        Private tipoFactorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Base() As String
            Get
                Return Me.baseField
            End Get
            Set
                Me.baseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Importe() As String
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TasaOCuota() As String
            Get
                Return Me.tasaOCuotaField
            End Get
            Set
                Me.tasaOCuotaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoFactor() As String
            Get
                Return Me.tipoFactorField
            End Get
            Set
                Me.tipoFactorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class traslado
        
        Private baseField As String
        
        Private importeField As String
        
        Private impuestoField As String
        
        Private tasaOCuotaField As String
        
        Private tipoFactorField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Base() As String
            Get
                Return Me.baseField
            End Get
            Set
                Me.baseField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Importe() As String
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Impuesto() As String
            Get
                Return Me.impuestoField
            End Get
            Set
                Me.impuestoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TasaOCuota() As String
            Get
                Return Me.tasaOCuotaField
            End Get
            Set
                Me.tasaOCuotaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoFactor() As String
            Get
                Return Me.tipoFactorField
            End Get
            Set
                Me.tipoFactorField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class parte
        
        Private informacionAduaneraField() As informacionAduanera
        
        Private cantidadField As String
        
        Private claveProdServField As String
        
        Private descripcionField As String
        
        Private importeField As String
        
        Private noIdentificacionField As String
        
        Private unidadField As String
        
        Private valorUnitarioField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>  _
        Public Property InformacionAduanera() As informacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set
                Me.informacionAduaneraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Cantidad() As String
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ClaveProdServ() As String
            Get
                Return Me.claveProdServField
            End Get
            Set
                Me.claveProdServField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Importe() As String
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NoIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set
                Me.noIdentificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set
                Me.unidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ValorUnitario() As String
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class informacionAduanera
        
        Private numeroPedimentoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NumeroPedimento() As String
            Get
                Return Me.numeroPedimentoField
            End Get
            Set
                Me.numeroPedimentoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class cuentaPredial
        
        Private numeroField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Numero() As String
            Get
                Return Me.numeroField
            End Get
            Set
                Me.numeroField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class aCuentaTerceros
        
        Private domicilioFiscalACuentaTercerosField As String
        
        Private nombreACuentaTercerosField As String
        
        Private regimenFiscalACuentaTercerosField As String
        
        Private rfcACuentaTercerosField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DomicilioFiscalACuentaTerceros() As String
            Get
                Return Me.domicilioFiscalACuentaTercerosField
            End Get
            Set
                Me.domicilioFiscalACuentaTercerosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NombreACuentaTerceros() As String
            Get
                Return Me.nombreACuentaTercerosField
            End Get
            Set
                Me.nombreACuentaTercerosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RegimenFiscalACuentaTerceros() As String
            Get
                Return Me.regimenFiscalACuentaTercerosField
            End Get
            Set
                Me.regimenFiscalACuentaTercerosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RfcACuentaTerceros() As String
            Get
                Return Me.rfcACuentaTercerosField
            End Get
            Set
                Me.rfcACuentaTercerosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class impuestosConcepto
        
        Private trasladosField() As traslado
        
        Private retencionesField() As retencion
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Traslado", IsNullable:=false)>  _
        Public Property Traslados() As traslado()
            Get
                Return Me.trasladosField
            End Get
            Set
                Me.trasladosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Retencion", IsNullable:=false)>  _
        Public Property Retenciones() As retencion()
            Get
                Return Me.retencionesField
            End Get
            Set
                Me.retencionesField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class concepto
        
        Private impuestosField As impuestosConcepto
        
        Private aCuentaTercerosField As aCuentaTerceros
        
        Private informacionAduaneraField() As informacionAduanera
        
        Private cuentaPredialField() As cuentaPredial
        
        Private parteField() As parte
        
        Private cantidadField As String
        
        Private claveProdServField As String
        
        Private claveUnidadField As String
        
        Private descripcionField As String
        
        Private descuentoField As String
        
        Private importeField As String
        
        Private noIdentificacionField As String
        
        Private objetoImpField As String
        
        Private unidadField As String
        
        Private valorUnitarioField As String
        
        '''<remarks/>
        Public Property Impuestos() As impuestosConcepto
            Get
                Return Me.impuestosField
            End Get
            Set
                Me.impuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property ACuentaTerceros() As aCuentaTerceros
            Get
                Return Me.aCuentaTercerosField
            End Get
            Set
                Me.aCuentaTercerosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("InformacionAduanera")>  _
        Public Property InformacionAduanera() As informacionAduanera()
            Get
                Return Me.informacionAduaneraField
            End Get
            Set
                Me.informacionAduaneraField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CuentaPredial")>  _
        Public Property CuentaPredial() As cuentaPredial()
            Get
                Return Me.cuentaPredialField
            End Get
            Set
                Me.cuentaPredialField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("Parte")>  _
        Public Property Parte() As parte()
            Get
                Return Me.parteField
            End Get
            Set
                Me.parteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Cantidad() As String
            Get
                Return Me.cantidadField
            End Get
            Set
                Me.cantidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ClaveProdServ() As String
            Get
                Return Me.claveProdServField
            End Get
            Set
                Me.claveProdServField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ClaveUnidad() As String
            Get
                Return Me.claveUnidadField
            End Get
            Set
                Me.claveUnidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Descripcion() As String
            Get
                Return Me.descripcionField
            End Get
            Set
                Me.descripcionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Descuento() As String
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Importe() As String
            Get
                Return Me.importeField
            End Get
            Set
                Me.importeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NoIdentificacion() As String
            Get
                Return Me.noIdentificacionField
            End Get
            Set
                Me.noIdentificacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ObjetoImp() As String
            Get
                Return Me.objetoImpField
            End Get
            Set
                Me.objetoImpField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Unidad() As String
            Get
                Return Me.unidadField
            End Get
            Set
                Me.unidadField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ValorUnitario() As String
            Get
                Return Me.valorUnitarioField
            End Get
            Set
                Me.valorUnitarioField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class receptor
        
        Private domicilioFiscalReceptorField As String
        
        Private nombreField As String
        
        Private numRegIdTribField As String
        
        Private regimenFiscalReceptorField As String
        
        Private residenciaFiscalField As String
        
        Private rfcField As String
        
        Private usoCFDIField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property DomicilioFiscalReceptor() As String
            Get
                Return Me.domicilioFiscalReceptorField
            End Get
            Set
                Me.domicilioFiscalReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NumRegIdTrib() As String
            Get
                Return Me.numRegIdTribField
            End Get
            Set
                Me.numRegIdTribField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RegimenFiscalReceptor() As String
            Get
                Return Me.regimenFiscalReceptorField
            End Get
            Set
                Me.regimenFiscalReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property ResidenciaFiscal() As String
            Get
                Return Me.residenciaFiscalField
            End Get
            Set
                Me.residenciaFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set
                Me.rfcField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UsoCFDI() As String
            Get
                Return Me.usoCFDIField
            End Get
            Set
                Me.usoCFDIField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class emisor
        
        Private facAtrAdquirenteField As String
        
        Private nombreField As String
        
        Private regimenFiscalField As String
        
        Private rfcField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FacAtrAdquirente() As String
            Get
                Return Me.facAtrAdquirenteField
            End Get
            Set
                Me.facAtrAdquirenteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Nombre() As String
            Get
                Return Me.nombreField
            End Get
            Set
                Me.nombreField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property RegimenFiscal() As String
            Get
                Return Me.regimenFiscalField
            End Get
            Set
                Me.regimenFiscalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Rfc() As String
            Get
                Return Me.rfcField
            End Get
            Set
                Me.rfcField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class cfdiRelacionado
        
        Private uUIDField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.uUIDField
            End Get
            Set
                Me.uUIDField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class cfdiRelacionados
        
        Private cfdiRelacionadoField() As cfdiRelacionado
        
        Private tipoRelacionField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CfdiRelacionado")>  _
        Public Property CfdiRelacionado() As cfdiRelacionado()
            Get
                Return Me.cfdiRelacionadoField
            End Get
            Set
                Me.cfdiRelacionadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoRelacion() As String
            Get
                Return Me.tipoRelacionField
            End Get
            Set
                Me.tipoRelacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class informacionGlobal
        
        Private anioField As String
        
        Private mesesField As String
        
        Private periodicidadField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Anio() As String
            Get
                Return Me.anioField
            End Get
            Set
                Me.anioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Meses() As String
            Get
                Return Me.mesesField
            End Get
            Set
                Me.mesesField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Periodicidad() As String
            Get
                Return Me.periodicidadField
            End Get
            Set
                Me.periodicidadField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://www.sat.gob.mx/cfd/4")>  _
    Partial Public Class comprobante
        
        Private informacionGlobalField As informacionGlobal
        
        Private cfdiRelacionadosField() As cfdiRelacionados
        
        Private emisorField As emisor
        
        Private receptorField As receptor
        
        Private conceptosField() As concepto
        
        Private impuestosField As impuestos
        
        Private complementoField() As timbreFiscalDigital
        
        Private certificadoField As String
        
        Private condicionesDePagoField As String
        
        Private confirmacionField As String
        
        Private descuentoField As String
        
        Private exportacionField As String
        
        Private fechaField As String
        
        Private folioField As String
        
        Private formaPagoField As String
        
        Private lugarExpedicionField As String
        
        Private metodoPagoField As String
        
        Private monedaField As String
        
        Private noCertificadoField As String
        
        Private selloField As String
        
        Private serieField As String
        
        Private subTotalField As String
        
        Private tipoCambioField As String
        
        Private tipoDeComprobanteField As String
        
        Private totalField As String
        
        Private versionField As String
        
        '''<remarks/>
        Public Property InformacionGlobal() As informacionGlobal
            Get
                Return Me.informacionGlobalField
            End Get
            Set
                Me.informacionGlobalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("CfdiRelacionados")>  _
        Public Property CfdiRelacionados() As cfdiRelacionados()
            Get
                Return Me.cfdiRelacionadosField
            End Get
            Set
                Me.cfdiRelacionadosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Emisor() As emisor
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Receptor() As receptor
            Get
                Return Me.receptorField
            End Get
            Set
                Me.receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("Concepto", IsNullable:=false)>  _
        Public Property Conceptos() As concepto()
            Get
                Return Me.conceptosField
            End Get
            Set
                Me.conceptosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property Impuestos() As impuestos
            Get
                Return Me.impuestosField
            End Get
            Set
                Me.impuestosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlArrayItemAttribute("TimbreFiscalDigital", [Namespace]:="http://www.sat.gob.mx/TimbreFiscalDigital", IsNullable:=false)>  _
        Public Property Complemento() As timbreFiscalDigital()
            Get
                Return Me.complementoField
            End Get
            Set
                Me.complementoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Certificado() As String
            Get
                Return Me.certificadoField
            End Get
            Set
                Me.certificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property CondicionesDePago() As String
            Get
                Return Me.condicionesDePagoField
            End Get
            Set
                Me.condicionesDePagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Confirmacion() As String
            Get
                Return Me.confirmacionField
            End Get
            Set
                Me.confirmacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Descuento() As String
            Get
                Return Me.descuentoField
            End Get
            Set
                Me.descuentoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Exportacion() As String
            Get
                Return Me.exportacionField
            End Get
            Set
                Me.exportacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Folio() As String
            Get
                Return Me.folioField
            End Get
            Set
                Me.folioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property FormaPago() As String
            Get
                Return Me.formaPagoField
            End Get
            Set
                Me.formaPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property LugarExpedicion() As String
            Get
                Return Me.lugarExpedicionField
            End Get
            Set
                Me.lugarExpedicionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property MetodoPago() As String
            Get
                Return Me.metodoPagoField
            End Get
            Set
                Me.metodoPagoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Moneda() As String
            Get
                Return Me.monedaField
            End Get
            Set
                Me.monedaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property NoCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Sello() As String
            Get
                Return Me.selloField
            End Get
            Set
                Me.selloField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Serie() As String
            Get
                Return Me.serieField
            End Get
            Set
                Me.serieField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property SubTotal() As String
            Get
                Return Me.subTotalField
            End Get
            Set
                Me.subTotalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoCambio() As String
            Get
                Return Me.tipoCambioField
            End Get
            Set
                Me.tipoCambioField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property TipoDeComprobante() As String
            Get
                Return Me.tipoDeComprobanteField
            End Get
            Set
                Me.tipoDeComprobanteField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlAttributeAttribute()>  _
        Public Property Version() As String
            Get
                Return Me.versionField
            End Get
            Set
                Me.versionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://service.timbrado.xpd.mx/")>  _
    Partial Public Class acuse
        
        Private codigoEstatusField As String
        
        Private esCancelableField As String
        
        Private estadoField As String
        
        Private estatusCancelacionField As String
        
        Private validacionEFOSField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property codigoEstatus() As String
            Get
                Return Me.codigoEstatusField
            End Get
            Set
                Me.codigoEstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property esCancelable() As String
            Get
                Return Me.esCancelableField
            End Get
            Set
                Me.esCancelableField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estado() As String
            Get
                Return Me.estadoField
            End Get
            Set
                Me.estadoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property estatusCancelacion() As String
            Get
                Return Me.estatusCancelacionField
            End Get
            Set
                Me.estatusCancelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Form:=System.Xml.Schema.XmlSchemaForm.Unqualified)>  _
        Public Property validacionEFOS() As String
            Get
                Return Me.validacionEFOSField
            End Get
            Set
                Me.validacionEFOSField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub validarCompletedEventHandler(ByVal sender As Object, ByVal e As validarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class validarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseValidar
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseValidar)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub timbrarCompletedEventHandler(ByVal sender As Object, ByVal e As timbrarCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class timbrarCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As responseTimbrar
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),responseTimbrar)
            End Get
        End Property
    End Class
End Namespace
