'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
'
Namespace mx.com.expidetufactura.cancelacionxpd.Produccion
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CancelacionPortSoap11", [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class CancelacionPortService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private envioEmailOperationCompleted As System.Threading.SendOrPostCallback
        
        Private obtenerPeticionesPendientesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private cancelarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private procesarRespuestaOperationCompleted As System.Threading.SendOrPostCallback
        
        Private obtenerCfdisRelacionadosOperationCompleted As System.Threading.SendOrPostCallback
        
        Private consultarCfdiOperationCompleted As System.Threading.SendOrPostCallback
        
        Private envioSmsOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FactuSax.My.MySettings.Default.FactuSax_mx_com_expidetufactura_cancelacionxpd_Produccion_CancelacionPortService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event envioEmailCompleted As envioEmailCompletedEventHandler
        
        '''<remarks/>
        Public Event obtenerPeticionesPendientesCompleted As obtenerPeticionesPendientesCompletedEventHandler
        
        '''<remarks/>
        Public Event cancelarCfdiCompleted As cancelarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event procesarRespuestaCompleted As procesarRespuestaCompletedEventHandler
        
        '''<remarks/>
        Public Event obtenerCfdisRelacionadosCompleted As obtenerCfdisRelacionadosCompletedEventHandler
        
        '''<remarks/>
        Public Event consultarCfdiCompleted As consultarCfdiCompletedEventHandler
        
        '''<remarks/>
        Public Event envioSmsCompleted As envioSmsCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function envioEmail(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal envioEmailRequest As envioEmailRequest) As <System.Xml.Serialization.XmlArrayAttribute("envioEmailResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("envioEmailResponse", IsNullable:=false)> serviceResponse()
            Dim results() As Object = Me.Invoke("envioEmail", New Object() {envioEmailRequest})
            Return CType(results(0),serviceResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub envioEmailAsync(ByVal envioEmailRequest As envioEmailRequest)
            Me.envioEmailAsync(envioEmailRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub envioEmailAsync(ByVal envioEmailRequest As envioEmailRequest, ByVal userState As Object)
            If (Me.envioEmailOperationCompleted Is Nothing) Then
                Me.envioEmailOperationCompleted = AddressOf Me.OnenvioEmailOperationCompleted
            End If
            Me.InvokeAsync("envioEmail", New Object() {envioEmailRequest}, Me.envioEmailOperationCompleted, userState)
        End Sub
        
        Private Sub OnenvioEmailOperationCompleted(ByVal arg As Object)
            If (Not (Me.envioEmailCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent envioEmailCompleted(Me, New envioEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function obtenerPeticionesPendientes(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal obtenerPeticionesPendientesRequest As obtenerPeticionesPendientesRequest) As <System.Xml.Serialization.XmlArrayAttribute("obtenerPeticionesPendientesResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("obtenerPeticionesPendientesResponse", IsNullable:=false)> cfdiResponse()
            Dim results() As Object = Me.Invoke("obtenerPeticionesPendientes", New Object() {obtenerPeticionesPendientesRequest})
            Return CType(results(0),cfdiResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerPeticionesPendientesAsync(ByVal obtenerPeticionesPendientesRequest As obtenerPeticionesPendientesRequest)
            Me.obtenerPeticionesPendientesAsync(obtenerPeticionesPendientesRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerPeticionesPendientesAsync(ByVal obtenerPeticionesPendientesRequest As obtenerPeticionesPendientesRequest, ByVal userState As Object)
            If (Me.obtenerPeticionesPendientesOperationCompleted Is Nothing) Then
                Me.obtenerPeticionesPendientesOperationCompleted = AddressOf Me.OnobtenerPeticionesPendientesOperationCompleted
            End If
            Me.InvokeAsync("obtenerPeticionesPendientes", New Object() {obtenerPeticionesPendientesRequest}, Me.obtenerPeticionesPendientesOperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerPeticionesPendientesOperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerPeticionesPendientesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerPeticionesPendientesCompleted(Me, New obtenerPeticionesPendientesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function cancelarCfdi(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal cancelarCfdiRequest As cancelarCfdiRequest) As <System.Xml.Serialization.XmlArrayAttribute("cancelarCfdiResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("cancelarCfdiResponse", IsNullable:=false)> cfdiResponse()
            Dim results() As Object = Me.Invoke("cancelarCfdi", New Object() {cancelarCfdiRequest})
            Return CType(results(0),cfdiResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub cancelarCfdiAsync(ByVal cancelarCfdiRequest As cancelarCfdiRequest)
            Me.cancelarCfdiAsync(cancelarCfdiRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub cancelarCfdiAsync(ByVal cancelarCfdiRequest As cancelarCfdiRequest, ByVal userState As Object)
            If (Me.cancelarCfdiOperationCompleted Is Nothing) Then
                Me.cancelarCfdiOperationCompleted = AddressOf Me.OncancelarCfdiOperationCompleted
            End If
            Me.InvokeAsync("cancelarCfdi", New Object() {cancelarCfdiRequest}, Me.cancelarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OncancelarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.cancelarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent cancelarCfdiCompleted(Me, New cancelarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function procesarRespuesta(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal procesarRespuestaRequest As procesarRespuestaRequest) As <System.Xml.Serialization.XmlArrayAttribute("procesarRespuestaResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("procesarRespuestaResponse", IsNullable:=false)> cfdiResponse()
            Dim results() As Object = Me.Invoke("procesarRespuesta", New Object() {procesarRespuestaRequest})
            Return CType(results(0),cfdiResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub procesarRespuestaAsync(ByVal procesarRespuestaRequest As procesarRespuestaRequest)
            Me.procesarRespuestaAsync(procesarRespuestaRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub procesarRespuestaAsync(ByVal procesarRespuestaRequest As procesarRespuestaRequest, ByVal userState As Object)
            If (Me.procesarRespuestaOperationCompleted Is Nothing) Then
                Me.procesarRespuestaOperationCompleted = AddressOf Me.OnprocesarRespuestaOperationCompleted
            End If
            Me.InvokeAsync("procesarRespuesta", New Object() {procesarRespuestaRequest}, Me.procesarRespuestaOperationCompleted, userState)
        End Sub
        
        Private Sub OnprocesarRespuestaOperationCompleted(ByVal arg As Object)
            If (Not (Me.procesarRespuestaCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent procesarRespuestaCompleted(Me, New procesarRespuestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function obtenerCfdisRelacionados(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal obtenerCfdisRelacionadosRequest As obtenerCfdisRelacionadosRequest) As <System.Xml.Serialization.XmlArrayAttribute("obtenerCfdisRelacionadosResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("obtenerCfdisRelacionadosResponse", IsNullable:=false)> cfdiResponse()
            Dim results() As Object = Me.Invoke("obtenerCfdisRelacionados", New Object() {obtenerCfdisRelacionadosRequest})
            Return CType(results(0),cfdiResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub obtenerCfdisRelacionadosAsync(ByVal obtenerCfdisRelacionadosRequest As obtenerCfdisRelacionadosRequest)
            Me.obtenerCfdisRelacionadosAsync(obtenerCfdisRelacionadosRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub obtenerCfdisRelacionadosAsync(ByVal obtenerCfdisRelacionadosRequest As obtenerCfdisRelacionadosRequest, ByVal userState As Object)
            If (Me.obtenerCfdisRelacionadosOperationCompleted Is Nothing) Then
                Me.obtenerCfdisRelacionadosOperationCompleted = AddressOf Me.OnobtenerCfdisRelacionadosOperationCompleted
            End If
            Me.InvokeAsync("obtenerCfdisRelacionados", New Object() {obtenerCfdisRelacionadosRequest}, Me.obtenerCfdisRelacionadosOperationCompleted, userState)
        End Sub
        
        Private Sub OnobtenerCfdisRelacionadosOperationCompleted(ByVal arg As Object)
            If (Not (Me.obtenerCfdisRelacionadosCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent obtenerCfdisRelacionadosCompleted(Me, New obtenerCfdisRelacionadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function consultarCfdi(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal consultarCfdiRequest As consultarCfdiRequest) As <System.Xml.Serialization.XmlArrayAttribute("consultarCfdiResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("consultarCfdiResponse", IsNullable:=false)> cfdiResponseQr()
            Dim results() As Object = Me.Invoke("consultarCfdi", New Object() {consultarCfdiRequest})
            Return CType(results(0),cfdiResponseQr())
        End Function
        
        '''<remarks/>
        Public Overloads Sub consultarCfdiAsync(ByVal consultarCfdiRequest As consultarCfdiRequest)
            Me.consultarCfdiAsync(consultarCfdiRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub consultarCfdiAsync(ByVal consultarCfdiRequest As consultarCfdiRequest, ByVal userState As Object)
            If (Me.consultarCfdiOperationCompleted Is Nothing) Then
                Me.consultarCfdiOperationCompleted = AddressOf Me.OnconsultarCfdiOperationCompleted
            End If
            Me.InvokeAsync("consultarCfdi", New Object() {consultarCfdiRequest}, Me.consultarCfdiOperationCompleted, userState)
        End Sub
        
        Private Sub OnconsultarCfdiOperationCompleted(ByVal arg As Object)
            If (Not (Me.consultarCfdiCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent consultarCfdiCompleted(Me, New consultarCfdiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
        Public Function envioSms(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://concretepage.com/soap")> ByVal envioSmsRequest As envioSmsRequest) As <System.Xml.Serialization.XmlArrayAttribute("envioSmsResponse", [Namespace]:="http://concretepage.com/soap"), System.Xml.Serialization.XmlArrayItemAttribute("envioSmsResponse", IsNullable:=false)> serviceResponse()
            Dim results() As Object = Me.Invoke("envioSms", New Object() {envioSmsRequest})
            Return CType(results(0),serviceResponse())
        End Function
        
        '''<remarks/>
        Public Overloads Sub envioSmsAsync(ByVal envioSmsRequest As envioSmsRequest)
            Me.envioSmsAsync(envioSmsRequest, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub envioSmsAsync(ByVal envioSmsRequest As envioSmsRequest, ByVal userState As Object)
            If (Me.envioSmsOperationCompleted Is Nothing) Then
                Me.envioSmsOperationCompleted = AddressOf Me.OnenvioSmsOperationCompleted
            End If
            Me.InvokeAsync("envioSms", New Object() {envioSmsRequest}, Me.envioSmsOperationCompleted, userState)
        End Sub
        
        Private Sub OnenvioSmsOperationCompleted(ByVal arg As Object)
            If (Not (Me.envioSmsCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent envioSmsCompleted(Me, New envioSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class envioEmailRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As emailParametros
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As emailParametros()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class emailParametros
        
        Private asuntoField As String
        
        Private mensajeField As String
        
        Private documentosAdjuntosField() As documentoAdjunto
        
        Private destinatariosField() As String
        
        Private copiadosField() As String
        
        Private copiadosOcultosField() As String
        
        '''<remarks/>
        Public Property asunto() As String
            Get
                Return Me.asuntoField
            End Get
            Set
                Me.asuntoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("documentosAdjuntos")>  _
        Public Property documentosAdjuntos() As documentoAdjunto()
            Get
                Return Me.documentosAdjuntosField
            End Get
            Set
                Me.documentosAdjuntosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("destinatarios")>  _
        Public Property destinatarios() As String()
            Get
                Return Me.destinatariosField
            End Get
            Set
                Me.destinatariosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("copiados")>  _
        Public Property copiados() As String()
            Get
                Return Me.copiadosField
            End Get
            Set
                Me.copiadosField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("copiadosOcultos")>  _
        Public Property copiadosOcultos() As String()
            Get
                Return Me.copiadosOcultosField
            End Get
            Set
                Me.copiadosOcultosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class documentoAdjunto
        
        Private documentoField() As Byte
        
        Private nombreArchivoField As String
        
        Private tipoField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="hexBinary")>  _
        Public Property documento() As Byte()
            Get
                Return Me.documentoField
            End Get
            Set
                Me.documentoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property nombreArchivo() As String
            Get
                Return Me.nombreArchivoField
            End Get
            Set
                Me.nombreArchivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class smsParametros
        
        Private mensajeField As String
        
        Private numerosField() As String
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("numeros")>  _
        Public Property numeros() As String()
            Get
                Return Me.numerosField
            End Get
            Set
                Me.numerosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class qrGenerico
        
        Private requestField As String
        
        Private responseField As String
        
        Private qrField As String
        
        '''<remarks/>
        Public Property request() As String
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property response() As String
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property qr() As String
            Get
                Return Me.qrField
            End Get
            Set
                Me.qrField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class responseGenericoQr
        
        Private servicioField As servicioGenerico
        
        Private qrGenericoField As qrGenerico
        
        '''<remarks/>
        Public Property servicio() As servicioGenerico
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property qrGenerico() As qrGenerico
            Get
                Return Me.qrGenericoField
            End Get
            Set
                Me.qrGenericoField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class servicioGenerico
        
        Private requestField As String
        
        Private responseField As String
        
        '''<remarks/>
        Public Property request() As String
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property response() As String
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class cfdiResponseQr
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private idTransaccionField As String
        
        Private responseGenericoQrField As responseGenericoQr
        
        Private bitacoraXsdField As bitacoraXsd
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idTransaccion() As String
            Get
                Return Me.idTransaccionField
            End Get
            Set
                Me.idTransaccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseGenericoQr() As responseGenericoQr
            Get
                Return Me.responseGenericoQrField
            End Get
            Set
                Me.responseGenericoQrField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bitacoraXsd() As bitacoraXsd
            Get
                Return Me.bitacoraXsdField
            End Get
            Set
                Me.bitacoraXsdField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class bitacoraXsd
        
        Private rutaField As String
        
        Private fechaField As Date
        
        Private contenidoField As String
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private correoField As String
        
        Private codigoEstatusField As String
        
        Private esCancelableField As String
        
        Private estatusCancelacionField As String
        
        Private idUsuarioField As String
        
        Private numeroSmsField As String
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private totalField As String
        
        Private transaccionField As String
        
        Private uuidCancelarField As String
        
        Private tipoOperacionField As String
        
        '''<remarks/>
        Public Property ruta() As String
            Get
                Return Me.rutaField
            End Get
            Set
                Me.rutaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha() As Date
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contenido() As String
            Get
                Return Me.contenidoField
            End Get
            Set
                Me.contenidoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property correo() As String
            Get
                Return Me.correoField
            End Get
            Set
                Me.correoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property codigoEstatus() As String
            Get
                Return Me.codigoEstatusField
            End Get
            Set
                Me.codigoEstatusField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property esCancelable() As String
            Get
                Return Me.esCancelableField
            End Get
            Set
                Me.esCancelableField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property estatusCancelacion() As String
            Get
                Return Me.estatusCancelacionField
            End Get
            Set
                Me.estatusCancelacionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idUsuario() As String
            Get
                Return Me.idUsuarioField
            End Get
            Set
                Me.idUsuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property numeroSms() As String
            Get
                Return Me.numeroSmsField
            End Get
            Set
                Me.numeroSmsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property transaccion() As String
            Get
                Return Me.transaccionField
            End Get
            Set
                Me.transaccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuidCancelar() As String
            Get
                Return Me.uuidCancelarField
            End Get
            Set
                Me.uuidCancelarField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipoOperacion() As String
            Get
                Return Me.tipoOperacionField
            End Get
            Set
                Me.tipoOperacionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class parametrosConsultarCfdi
        
        Private noCertificadoField As String
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private totalField As String
        
        Private uuidField As String
        
        Private xmlB64Field As String
        
        '''<remarks/>
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlB64() As String
            Get
                Return Me.xmlB64Field
            End Get
            Set
                Me.xmlB64Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class parametrosObtenerCfdisRelacionados
        
        Private noCertificadoField As String
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private uuidField As String
        
        Private xmlB64Field As String
        
        '''<remarks/>
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlB64() As String
            Get
                Return Me.xmlB64Field
            End Get
            Set
                Me.xmlB64Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class folio
        
        Private uuidField As String
        
        Private respuestaField As String
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property respuesta() As String
            Get
                Return Me.respuestaField
            End Get
            Set
                Me.respuestaField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class parametrosProcesarRespuesta
        
        Private noCertificadoField As String
        
        Private rfcReceptorField As String
        
        Private fechaField As String
        
        Private foliosField() As folio
        
        Private xmlB64Field As String
        
        '''<remarks/>
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("folios")>  _
        Public Property folios() As folio()
            Get
                Return Me.foliosField
            End Get
            Set
                Me.foliosField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlB64() As String
            Get
                Return Me.xmlB64Field
            End Get
            Set
                Me.xmlB64Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class parametrosCancelaCfdi
        
        Private noCertificadoField As String
        
        Private rfcEmisorField As String
        
        Private rfcReceptorField As String
        
        Private totalField As String
        
        Private uuidField As String
        
        Private motivoField As String
        
        Private folioSustitucionField As String
        
        Private xmlB64Field As String
        
        '''<remarks/>
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcEmisor() As String
            Get
                Return Me.rfcEmisorField
            End Get
            Set
                Me.rfcEmisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property total() As String
            Get
                Return Me.totalField
            End Get
            Set
                Me.totalField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property motivo() As String
            Get
                Return Me.motivoField
            End Get
            Set
                Me.motivoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property folioSustitucion() As String
            Get
                Return Me.folioSustitucionField
            End Get
            Set
                Me.folioSustitucionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlB64() As String
            Get
                Return Me.xmlB64Field
            End Get
            Set
                Me.xmlB64Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class xmlRelacionado
        
        Private xmlField As String
        
        Private uuidField As String
        
        Private emisorField As String
        
        Private receptorField As String
        
        Private tipoField As String
        
        Private pdfField() As Byte
        
        '''<remarks/>
        Public Property xml() As String
            Get
                Return Me.xmlField
            End Get
            Set
                Me.xmlField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property uuid() As String
            Get
                Return Me.uuidField
            End Get
            Set
                Me.uuidField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property emisor() As String
            Get
                Return Me.emisorField
            End Get
            Set
                Me.emisorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property receptor() As String
            Get
                Return Me.receptorField
            End Get
            Set
                Me.receptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property tipo() As String
            Get
                Return Me.tipoField
            End Get
            Set
                Me.tipoField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="hexBinary")>  _
        Public Property pdf() As Byte()
            Get
                Return Me.pdfField
            End Get
            Set
                Me.pdfField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class tokenGenerico
        
        Private requestField As String
        
        Private responseField As String
        
        Private tokenField As String
        
        '''<remarks/>
        Public Property request() As String
            Get
                Return Me.requestField
            End Get
            Set
                Me.requestField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property response() As String
            Get
                Return Me.responseField
            End Get
            Set
                Me.responseField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property token() As String
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class responseGenerico
        
        Private servicioField As servicioGenerico
        
        Private tokenField As tokenGenerico
        
        '''<remarks/>
        Public Property servicio() As servicioGenerico
            Get
                Return Me.servicioField
            End Get
            Set
                Me.servicioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property token() As tokenGenerico
            Get
                Return Me.tokenField
            End Get
            Set
                Me.tokenField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class cfdiResponse
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private idTransaccionField As String
        
        Private responseGenericoField As responseGenerico
        
        Private bitacoraXsdField As bitacoraXsd
        
        Private xmlRelacionadosField() As xmlRelacionado
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idTransaccion() As String
            Get
                Return Me.idTransaccionField
            End Get
            Set
                Me.idTransaccionField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property responseGenerico() As responseGenerico
            Get
                Return Me.responseGenericoField
            End Get
            Set
                Me.responseGenericoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property bitacoraXsd() As bitacoraXsd
            Get
                Return Me.bitacoraXsdField
            End Get
            Set
                Me.bitacoraXsdField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("xmlRelacionados")>  _
        Public Property xmlRelacionados() As xmlRelacionado()
            Get
                Return Me.xmlRelacionadosField
            End Get
            Set
                Me.xmlRelacionadosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class parametrosObtenerPeticionesPendientes
        
        Private noCertificadoField As String
        
        Private rfcReceptorField As String
        
        Private fechaField As String
        
        Private xmlB64Field As String
        
        '''<remarks/>
        Public Property noCertificado() As String
            Get
                Return Me.noCertificadoField
            End Get
            Set
                Me.noCertificadoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property rfcReceptor() As String
            Get
                Return Me.rfcReceptorField
            End Get
            Set
                Me.rfcReceptorField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fecha() As String
            Get
                Return Me.fechaField
            End Get
            Set
                Me.fechaField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property xmlB64() As String
            Get
                Return Me.xmlB64Field
            End Get
            Set
                Me.xmlB64Field = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class serviceResponse
        
        Private codigoField As String
        
        Private mensajeField As String
        
        Private idTransaccionField As String
        
        '''<remarks/>
        Public Property codigo() As String
            Get
                Return Me.codigoField
            End Get
            Set
                Me.codigoField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property mensaje() As String
            Get
                Return Me.mensajeField
            End Get
            Set
                Me.mensajeField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property idTransaccion() As String
            Get
                Return Me.idTransaccionField
            End Get
            Set
                Me.idTransaccionField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class obtenerPeticionesPendientesRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As parametrosObtenerPeticionesPendientes
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As parametrosObtenerPeticionesPendientes()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class cancelarCfdiRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As parametrosCancelaCfdi
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As parametrosCancelaCfdi()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class procesarRespuestaRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As parametrosProcesarRespuesta
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As parametrosProcesarRespuesta()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class obtenerCfdisRelacionadosRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As parametrosObtenerCfdisRelacionados
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As parametrosObtenerCfdisRelacionados()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class consultarCfdiRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As parametrosConsultarCfdi
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As parametrosConsultarCfdi()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute(AnonymousType:=true, [Namespace]:="http://concretepage.com/soap")>  _
    Partial Public Class envioSmsRequest
        
        Private usuarioField As String
        
        Private contrasenaField As String
        
        Private parametrosField() As smsParametros
        
        '''<remarks/>
        Public Property usuario() As String
            Get
                Return Me.usuarioField
            End Get
            Set
                Me.usuarioField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property contrasena() As String
            Get
                Return Me.contrasenaField
            End Get
            Set
                Me.contrasenaField = value
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("parametros")>  _
        Public Property parametros() As smsParametros()
            Get
                Return Me.parametrosField
            End Get
            Set
                Me.parametrosField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub envioEmailCompletedEventHandler(ByVal sender As Object, ByVal e As envioEmailCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class envioEmailCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As serviceResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),serviceResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub obtenerPeticionesPendientesCompletedEventHandler(ByVal sender As Object, ByVal e As obtenerPeticionesPendientesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerPeticionesPendientesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cfdiResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cfdiResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub cancelarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As cancelarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class cancelarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cfdiResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cfdiResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub procesarRespuestaCompletedEventHandler(ByVal sender As Object, ByVal e As procesarRespuestaCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class procesarRespuestaCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cfdiResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cfdiResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub obtenerCfdisRelacionadosCompletedEventHandler(ByVal sender As Object, ByVal e As obtenerCfdisRelacionadosCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class obtenerCfdisRelacionadosCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cfdiResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cfdiResponse())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub consultarCfdiCompletedEventHandler(ByVal sender As Object, ByVal e As consultarCfdiCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class consultarCfdiCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As cfdiResponseQr()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),cfdiResponseQr())
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")>  _
    Public Delegate Sub envioSmsCompletedEventHandler(ByVal sender As Object, ByVal e As envioSmsCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class envioSmsCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As serviceResponse()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),serviceResponse())
            End Get
        End Property
    End Class
End Namespace
